### PR TITLE
First user, client, tip annotations

### PR DESCRIPTION
**Pull request by SendoaBadiola**
Merge the first annotations from user, client and tip to main branch

### CODE REVIEW

**Comment by ghost** [comment]
Not Ameisin, There is an error in the entities Client and User where in the @Table annotation the schema name is wrong

**Comment by HaizeaF** [comment]
The schema in user and client is incorrect.

**Comment by ghost** [comment]
Now Corrected

**Comment by HaizeaF** [comment]
Perfect

**Comment by SendoaBadiola** [comment]
Fine

**Pull request merged**
